version: "3.1"
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mystore
    ports:
      - 5432:5432
